#!/usr/bin/env bash
# markdown.bash - Utilities for reading and manipulating markdown documents
# Version: 1.1.0
# Description: Functions for parsing and editing markdown files, with specific
#              support for implementation plan documents generated by Copilot
#              skills (devenv-create-implementation-plan, devenv-plan-from-spec).
#              Covers both task checkboxes and acceptance-criteria checkboxes.
# Requirements: Bash 4.0+

# Guard against multiple sourcing
if [ -n "${_MARKDOWN_LOADED:-}" ]; then
    return 0
fi
_MARKDOWN_LOADED=1

# Ensure error handling is available
if [ -z "${_ERROR_HANDLING_LOADED:-}" ] && [ -f "${DEVENV_TOOLS}/lib/error-handling.bash" ]; then
    # shellcheck disable=SC1091
    source "${DEVENV_TOOLS}/lib/error-handling.bash"
fi

# ============================================================================
# Implementation Plan — Task Identification
# ============================================================================

# Validate that a string is a well-formed task number (X.Y or X.Y.Z).
#
# Usage:
#   validate_plan_task_number TASK_NUMBER
#
# Arguments:
#   TASK_NUMBER   Task number string, e.g. "2.3" or "2.3.1"
#
# Returns:
#   0 if valid, 1 if invalid
validate_plan_task_number() {
    local task_number="${1:-}"
    if [[ "$task_number" =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
        return 0
    fi
    log_error "Invalid task number: '$task_number'. Expected format X.Y or X.Y.Z"
    return 1
}

# Build the regex pattern used to locate a task checkbox line for the given
# task number.  The pattern matches lines like:
#
#   - [ ] **2.3 [M] Do something**
#   - [x] **2.3 [M] Do something**
#   - [ ] **1.2.1 [S] Sub-task**
#
# The task number is treated as a literal prefix; anything may follow it on
# the same line.
#
# Usage:
#   _plan_task_pattern TASK_NUMBER
#
# Output (stdout): the grep-compatible extended regex pattern
_plan_task_pattern() {
    local task_number="${1:?task_number required}"
    # Escape any dots so they are treated as literals in regex
    local escaped
    escaped="${task_number//./\\.}"
    printf '^[[:space:]]*- \[[ x]\][[:space:]]+\*\*%s[[:space:]]' "$escaped"
}

# Internal helper: find the 1-based line number of the first checkbox line
# matching PATTERN.  LABEL is used only in the error message.
#
# Usage:
#   _find_plan_item_line PLAN_FILE PATTERN LABEL
_find_plan_item_line() {
    local plan_file="${1:?plan_file required}"
    local pattern="${2:?pattern required}"
    local label="${3:?label required}"

    local line_number
    line_number=$(grep -nE "$pattern" "$plan_file" | head -1 | cut -d: -f1)

    if [ -z "$line_number" ]; then
        log_error "$label not found in $plan_file"
        return 1
    fi

    printf '%s\n' "$line_number"
}

# Find the line number of a task checkbox in an implementation plan file.
#
# Usage:
#   find_plan_task_line PLAN_FILE TASK_NUMBER
#
# Arguments:
#   PLAN_FILE     Path to the markdown implementation plan
#   TASK_NUMBER   Task identifier, e.g. "2.3" or "2.3.1"
#
# Output (stdout): the 1-based line number, or nothing if not found
#
# Returns:
#   0 if found, 1 if the file does not exist or the task is not found
find_plan_task_line() {
    local plan_file="${1:?plan_file required}"
    local task_number="${2:?task_number required}"

    if [ ! -f "$plan_file" ]; then
        log_error "Plan file not found: $plan_file"
        return 1
    fi

    validate_plan_task_number "$task_number" || return 1

    local pattern
    pattern="$(_plan_task_pattern "$task_number")"

    _find_plan_item_line "$plan_file" "$pattern" "Task $task_number"
}

# Check whether a task checkbox is already marked complete.
#
# Usage:
#   is_plan_task_complete PLAN_FILE TASK_NUMBER
#
# Returns:
#   0 if the task is marked [x], 1 if it is marked [ ], 2 on error
is_plan_task_complete() {
    local plan_file="${1:?plan_file required}"
    local task_number="${2:?task_number required}"

    local line_number
    line_number=$(find_plan_task_line "$plan_file" "$task_number") || return 2

    local line
    line=$(sed -n "${line_number}p" "$plan_file")

    if [[ "$line" =~ \[x\] ]]; then
        return 0
    fi
    return 1
}

# Internal helper: toggle the checkbox on a specific line to the given state.
# LABEL is used only for log messages.
#
# Usage:
#   _set_plan_item_complete_at_line PLAN_FILE LINE_NUMBER STATE LABEL
_set_plan_item_complete_at_line() {
    local plan_file="${1:?plan_file required}"
    local line_number="${2:?line_number required}"
    local state="${3:-complete}"
    local label="${4:?label required}"

    local line
    line=$(sed -n "${line_number}p" "$plan_file")

    local new_box
    if [ "$state" = "complete" ]; then
        new_box="[x]"
    else
        new_box="[ ]"
    fi

    if [ "$state" = "complete" ] && [[ "$line" =~ \[x\] ]]; then
        log_info "$label is already marked complete"
        return 0
    fi
    if [ "$state" = "incomplete" ] && [[ "$line" =~ \[\ \] ]]; then
        log_info "$label is already marked incomplete"
        return 0
    fi

    local tmp_file
    tmp_file="$(mktemp)"

    awk -v lineno="$line_number" \
        -v new_box="$new_box" \
        'NR == lineno { sub(/\[[ x]\]/, new_box) } { print }' \
        "$plan_file" > "$tmp_file"

    mv "$tmp_file" "$plan_file"

    log_info "$label marked as ${state}"
    return 0
}

# Mark a task checkbox as complete ([x]) or incomplete ([ ]).
#
# Usage:
#   set_plan_task_complete PLAN_FILE TASK_NUMBER [complete|incomplete]
#
# Arguments:
#   PLAN_FILE     Path to the markdown implementation plan
#   TASK_NUMBER   Task identifier, e.g. "2.3" or "2.3.1"
#   STATE         "complete" (default) or "incomplete"
#
# Returns:
#   0 on success, 1 on error
set_plan_task_complete() {
    local plan_file="${1:?plan_file required}"
    local task_number="${2:?task_number required}"
    local state="${3:-complete}"

    if [ ! -f "$plan_file" ]; then
        log_error "Plan file not found: $plan_file"
        return 1
    fi

    validate_plan_task_number "$task_number" || return 1

    local line_number
    line_number=$(find_plan_task_line "$plan_file" "$task_number") || return 1

    _set_plan_item_complete_at_line "$plan_file" "$line_number" "$state" "Task $task_number"
}

# ============================================================================
# Implementation Plan — Acceptance Criteria
# ============================================================================

# Validate that a string is a well-formed acceptance-criteria number.
# Accepted formats: AC-N, AC-N.N, AC-N.N.N (any number of dot-separated
# integer segments after the "AC-" prefix).
#
# Usage:
#   validate_plan_ac_number AC_NUMBER
#
# Returns:
#   0 if valid, 1 if invalid
validate_plan_ac_number() {
    local ac_number="${1:-}"
    if [[ "$ac_number" =~ ^AC-[0-9]+(\.[0-9]+)*$ ]]; then
        return 0
    fi
    log_error "Invalid AC number: '$ac_number'. Expected format AC-N, AC-N.N, or AC-N.N.N"
    return 1
}

# Build the regex pattern used to locate a specific acceptance-criteria
# checkbox line.
#
# Usage:
#   _plan_ac_pattern AC_NUMBER
#
# Output (stdout): the grep-compatible extended regex pattern
_plan_ac_pattern() {
    local ac_number="${1:?ac_number required}"
    local escaped="${ac_number//./\\.}"
    printf '^[[:space:]]*- \[[ x]\][[:space:]]+.*\*\*%s\*\*' "$escaped"
}

# Build the regex pattern used to count any acceptance-criteria checkbox line.
#
# Usage:
#   _plan_ac_checkbox_pattern
#
# Output (stdout): the grep-compatible extended regex pattern
_plan_ac_checkbox_pattern() {
    printf '^[[:space:]]*- \[[ x]\][[:space:]]+.*\*\*AC-[0-9]+(\.[0-9]+)*\*\*'
}

# Find the line number of an acceptance-criteria checkbox in a plan file.
#
# Usage:
#   find_plan_ac_line PLAN_FILE AC_NUMBER
#
# Arguments:
#   PLAN_FILE   Path to the markdown file
#   AC_NUMBER   Acceptance-criteria identifier, e.g. "AC-3" or "AC-1.2"
#
# Output (stdout): the 1-based line number, or nothing if not found
#
# Returns:
#   0 if found, 1 if the file does not exist or the item is not found
find_plan_ac_line() {
    local plan_file="${1:?plan_file required}"
    local ac_number="${2:?ac_number required}"

    if [ ! -f "$plan_file" ]; then
        log_error "Plan file not found: $plan_file"
        return 1
    fi

    validate_plan_ac_number "$ac_number" || return 1

    local pattern
    pattern="$(_plan_ac_pattern "$ac_number")"

    _find_plan_item_line "$plan_file" "$pattern" "$ac_number"
}

# Check whether an acceptance-criteria checkbox is already marked complete.
#
# Usage:
#   is_plan_ac_complete PLAN_FILE AC_NUMBER
#
# Returns:
#   0 if marked [x], 1 if marked [ ], 2 on error
is_plan_ac_complete() {
    local plan_file="${1:?plan_file required}"
    local ac_number="${2:?ac_number required}"

    local line_number
    line_number=$(find_plan_ac_line "$plan_file" "$ac_number") || return 2

    local line
    line=$(sed -n "${line_number}p" "$plan_file")

    if [[ "$line" =~ \[x\] ]]; then
        return 0
    fi
    return 1
}

# Mark an acceptance-criteria checkbox as complete ([x]) or incomplete ([ ]).
#
# Usage:
#   set_plan_ac_complete PLAN_FILE AC_NUMBER [complete|incomplete]
#
# Arguments:
#   PLAN_FILE   Path to the markdown file
#   AC_NUMBER   Acceptance-criteria identifier, e.g. "AC-3" or "AC-1.2"
#   STATE       "complete" (default) or "incomplete"
#
# Returns:
#   0 on success, 1 on error
set_plan_ac_complete() {
    local plan_file="${1:?plan_file required}"
    local ac_number="${2:?ac_number required}"
    local state="${3:-complete}"

    if [ ! -f "$plan_file" ]; then
        log_error "Plan file not found: $plan_file"
        return 1
    fi

    validate_plan_ac_number "$ac_number" || return 1

    local line_number
    line_number=$(find_plan_ac_line "$plan_file" "$ac_number") || return 1

    _set_plan_item_complete_at_line "$plan_file" "$line_number" "$state" "$ac_number"
}

# ============================================================================
# Implementation Plan — Querying
# ============================================================================

# Count total tasks and completed tasks in an implementation plan.
#
# Usage:
#   count_plan_tasks PLAN_FILE
#
# Output (stdout): two space-separated integers: COMPLETED TOTAL
#
# Returns:
#   0 on success, 1 if file not found
count_plan_tasks() {
    local plan_file="${1:?plan_file required}"

    if [ ! -f "$plan_file" ]; then
        log_error "Plan file not found: $plan_file"
        return 1
    fi

    local total completed
    total=$(grep -cE '^[[:space:]]*- \[[ x]\]' "$plan_file" || true)
    completed=$(grep -cE '^[[:space:]]*- \[x\]' "$plan_file" || true)

    printf '%s %s\n' "$completed" "$total"
}

# Count total acceptance-criteria items and completed ones in a plan file.
# Only lines matching the AC checkbox pattern are counted; regular task
# checkboxes are excluded.
#
# Usage:
#   count_plan_acs PLAN_FILE
#
# Output (stdout): two space-separated integers: COMPLETED TOTAL
#
# Returns:
#   0 on success, 1 if file not found
count_plan_acs() {
    local plan_file="${1:?plan_file required}"

    if [ ! -f "$plan_file" ]; then
        log_error "Plan file not found: $plan_file"
        return 1
    fi

    local total completed
    local pattern
    pattern="$(_plan_ac_checkbox_pattern)"

    total=$(grep -cE "$pattern" "$plan_file" || true)
    completed=$(grep -cE '^[[:space:]]*- \[x\][[:space:]]+.*\*\*AC-[0-9]+(\.[0-9]+)*\*\*' "$plan_file" || true)

    printf '%s %s\n' "$completed" "$total"
}
