#!/usr/bin/env bash
# markdown.bash - Utilities for reading and manipulating markdown documents
# Version: 1.0.0
# Description: Functions for parsing and editing markdown files, with specific
#              support for implementation plan documents generated by Copilot
#              skills (devenv-create-implementation-plan, devenv-plan-from-spec).
# Requirements: Bash 4.0+

# Guard against multiple sourcing
if [ -n "${_MARKDOWN_LOADED:-}" ]; then
    return 0
fi
_MARKDOWN_LOADED=1

# Ensure error handling is available
if [ -z "${_ERROR_HANDLING_LOADED:-}" ] && [ -f "${DEVENV_TOOLS}/lib/error-handling.bash" ]; then
    # shellcheck disable=SC1091
    source "${DEVENV_TOOLS}/lib/error-handling.bash"
fi

# ============================================================================
# Implementation Plan — Task Identification
# ============================================================================

# Validate that a string is a well-formed task number (X.Y or X.Y.Z).
#
# Usage:
#   validate_plan_task_number TASK_NUMBER
#
# Arguments:
#   TASK_NUMBER   Task number string, e.g. "2.3" or "2.3.1"
#
# Returns:
#   0 if valid, 1 if invalid
validate_plan_task_number() {
    local task_number="${1:-}"
    if [[ "$task_number" =~ ^[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
        return 0
    fi
    log_error "Invalid task number: '$task_number'. Expected format X.Y or X.Y.Z"
    return 1
}

# Build the regex pattern used to locate a task checkbox line for the given
# task number.  The pattern matches lines like:
#
#   - [ ] **2.3 [M] Do something**
#   - [x] **2.3 [M] Do something**
#   - [ ] **1.2.1 [S] Sub-task**
#
# The task number is treated as a literal prefix; anything may follow it on
# the same line.
#
# Usage:
#   _plan_task_pattern TASK_NUMBER
#
# Output (stdout): the grep-compatible extended regex pattern
_plan_task_pattern() {
    local task_number="${1:?task_number required}"
    # Escape any dots so they are treated as literals in regex
    local escaped
    escaped="${task_number//./\\.}"
    printf '^[[:space:]]*- \[[ x]\][[:space:]]+\*\*%s[[:space:]]' "$escaped"
}

# Find the line number of a task checkbox in an implementation plan file.
#
# Usage:
#   find_plan_task_line PLAN_FILE TASK_NUMBER
#
# Arguments:
#   PLAN_FILE     Path to the markdown implementation plan
#   TASK_NUMBER   Task identifier, e.g. "2.3" or "2.3.1"
#
# Output (stdout): the 1-based line number, or nothing if not found
#
# Returns:
#   0 if found, 1 if the file does not exist or the task is not found
find_plan_task_line() {
    local plan_file="${1:?plan_file required}"
    local task_number="${2:?task_number required}"

    if [ ! -f "$plan_file" ]; then
        log_error "Plan file not found: $plan_file"
        return 1
    fi

    validate_plan_task_number "$task_number" || return 1

    local pattern
    pattern="$(_plan_task_pattern "$task_number")"

    local line_number
    line_number=$(grep -nE "$pattern" "$plan_file" | head -1 | cut -d: -f1)

    if [ -z "$line_number" ]; then
        log_error "Task $task_number not found in $plan_file"
        return 1
    fi

    printf '%s\n' "$line_number"
}

# Check whether a task checkbox is already marked complete.
#
# Usage:
#   is_plan_task_complete PLAN_FILE TASK_NUMBER
#
# Returns:
#   0 if the task is marked [x], 1 if it is marked [ ], 2 on error
is_plan_task_complete() {
    local plan_file="${1:?plan_file required}"
    local task_number="${2:?task_number required}"

    local line_number
    line_number=$(find_plan_task_line "$plan_file" "$task_number") || return 2

    local line
    line=$(sed -n "${line_number}p" "$plan_file")

    if [[ "$line" =~ \[x\] ]]; then
        return 0
    fi
    return 1
}

# Mark a task checkbox as complete ([x]) or incomplete ([ ]).
#
# This function performs an in-place edit of the plan file.  It replaces only
# the first checkbox on the task line — it does not touch any other line.
#
# Usage:
#   set_plan_task_complete PLAN_FILE TASK_NUMBER [complete|incomplete]
#
# Arguments:
#   PLAN_FILE     Path to the markdown implementation plan
#   TASK_NUMBER   Task identifier, e.g. "2.3" or "2.3.1"
#   STATE         "complete" (default) or "incomplete"
#
# Returns:
#   0 on success, 1 on error
set_plan_task_complete() {
    local plan_file="${1:?plan_file required}"
    local task_number="${2:?task_number required}"
    local state="${3:-complete}"

    if [ ! -f "$plan_file" ]; then
        log_error "Plan file not found: $plan_file"
        return 1
    fi

    validate_plan_task_number "$task_number" || return 1

    local line_number
    line_number=$(find_plan_task_line "$plan_file" "$task_number") || return 1

    local line
    line=$(sed -n "${line_number}p" "$plan_file")

    # Determine new checkbox value
    local new_box old_box
    if [ "$state" = "complete" ]; then
        old_box="[ ]"
        new_box="[x]"
    else
        old_box="[x]"
        new_box="[ ]"
    fi

    # Check if already in the desired state
    if [ "$state" = "complete" ] && [[ "$line" =~ \[x\] ]]; then
        log_info "Task $task_number is already marked complete"
        return 0
    fi
    if [ "$state" = "incomplete" ] && [[ "$line" =~ \[\ \] ]]; then
        log_info "Task $task_number is already marked incomplete"
        return 0
    fi

    # Replace the first checkbox on that specific line only
    # Use a temp file for portability (sed -i behaves differently on macOS vs Linux)
    local tmp_file
    tmp_file="$(mktemp)"

    awk -v lineno="$line_number" \
        -v old_box="$old_box" \
        -v new_box="$new_box" \
        'NR == lineno { sub(/\[[ x]\]/, new_box) } { print }' \
        "$plan_file" > "$tmp_file"

    mv "$tmp_file" "$plan_file"

    log_info "Task $task_number marked as ${state}"
    return 0
}

# ============================================================================
# Implementation Plan — Querying
# ============================================================================

# Count total tasks and completed tasks in an implementation plan.
#
# Usage:
#   count_plan_tasks PLAN_FILE
#
# Output (stdout): two space-separated integers: COMPLETED TOTAL
#
# Returns:
#   0 on success, 1 if file not found
count_plan_tasks() {
    local plan_file="${1:?plan_file required}"

    if [ ! -f "$plan_file" ]; then
        log_error "Plan file not found: $plan_file"
        return 1
    fi

    local total completed
    total=$(grep -cE '^[[:space:]]*- \[[ x]\]' "$plan_file" || true)
    completed=$(grep -cE '^[[:space:]]*- \[x\]' "$plan_file" || true)

    printf '%s %s\n' "$completed" "$total"
}
