#!/usr/bin/env bash
# markdown-plan-complete-task.sh - Mark one or more tasks in an implementation plan as complete or incomplete
# Version: 1.1.0
# Description: Toggles the checkbox state of one or more tasks in a markdown
#              implementation plan generated by Copilot skills such as
#              devenv-create-implementation-plan.
# Requirements: Bash 4.0+, awk, grep, sed

source "$DEVENV_TOOLS/lib/error-handling.bash"
source "$DEVENV_TOOLS/lib/versioning.bash"

enable_strict_mode

readonly SCRIPT_VERSION="1.0.0"
# shellcheck disable=SC2155
readonly SCRIPT_NAME="$(basename "$0")"

script_version "$SCRIPT_NAME" "$SCRIPT_VERSION" "Mark one or more tasks in an implementation plan as complete or incomplete"

source "$DEVENV_TOOLS/lib/markdown.bash"

# ============================================================================
# Global Variables
# ============================================================================

PLAN_FILE=""
TASK_NUMBERS=()
UNCOMPLETE=0
VERBOSE=0

# ============================================================================
# Usage
# ============================================================================

show_usage() {
    cat << EOF
Usage: $SCRIPT_NAME [OPTIONS] TASK_NUMBER... [PLAN_FILE]

Mark one or more task checkboxes in an implementation plan as complete or incomplete.

Tasks are identified by their dotted number, e.g. "2.3" or "1.4.2", as they
appear in plans generated by devenv-create-implementation-plan.

Positional arguments are classified automatically: any argument matching the
X.Y or X.Y.Z pattern is treated as a task number; anything else is treated as
the plan file path.  At most one plan file may be given.  If no plan file is
given, the first Implementation_plan-*.md found in the current directory is used.

Arguments:
    TASK_NUMBER...  One or more dotted task numbers to update (X.Y or X.Y.Z)
    PLAN_FILE       Path to the markdown plan file (optional).

Options:
    -h, --help          Show this help message and exit
    -v, --version       Show version information and exit
    -V, --verbose       Enable verbose output
    --uncomplete        Mark the tasks as incomplete ([ ]) instead of complete ([x])

Examples:
    # Mark task 2.3 complete in the auto-detected plan file
    $SCRIPT_NAME 2.3

    # Mark several tasks complete at once
    $SCRIPT_NAME 1.1 1.2 1.3

    # Mark tasks complete in a specific plan file (file can appear anywhere)
    $SCRIPT_NAME 1.1 1.2 /path/to/Implementation_plan-001.md

    # Undo (mark incomplete)
    $SCRIPT_NAME --uncomplete 2.3 2.4

Exit Codes:
    0   All tasks updated successfully
    1   One or more tasks failed (task not found, etc.)
    2   Invalid arguments
    4   Plan file not found

EOF
    exit 0
}

# ============================================================================
# Argument Parsing
# ============================================================================

parse_args() {
    local positional=()

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h|--help)
                show_usage
                ;;
            -v|--version)
                exit 0
                ;;
            -V|--verbose)
                VERBOSE=1
                shift
                ;;
            --uncomplete)
                UNCOMPLETE=1
                shift
                ;;
            -*)
                log_error "Unknown option: $1"
                log_info "Run '$SCRIPT_NAME --help' for usage."
                exit "$EXIT_INVALID_ARGUMENT"
                ;;
            *)
                positional+=("$1")
                shift
                ;;
        esac
    done

    if [ "${#positional[@]}" -eq 0 ]; then
        log_error "At least one TASK_NUMBER is required."
        log_info "Run '$SCRIPT_NAME --help' for usage."
        exit "$EXIT_INVALID_ARGUMENT"
    fi

    # Classify each positional arg: task numbers match X.Y or X.Y.Z; anything
    # else is the plan file.  Error on more than one non-task argument.
    for arg in "${positional[@]}"; do
        if validate_plan_task_number "$arg" 2>/dev/null; then
            TASK_NUMBERS+=("$arg")
        else
            if [ -n "$PLAN_FILE" ]; then
                log_error "Unexpected argument '$arg': plan file already set to '$PLAN_FILE'."
                log_info "Run '$SCRIPT_NAME --help' for usage."
                exit "$EXIT_INVALID_ARGUMENT"
            fi
            PLAN_FILE="$arg"
        fi
    done

    if [ "${#TASK_NUMBERS[@]}" -eq 0 ]; then
        log_error "At least one TASK_NUMBER is required."
        log_info "Run '$SCRIPT_NAME --help' for usage."
        exit "$EXIT_INVALID_ARGUMENT"
    fi
}

# ============================================================================
# Helpers
# ============================================================================

# Resolve the plan file: use the explicit argument if given, otherwise find
# the first Implementation_plan-*.md in the current directory.
resolve_plan_file() {
    if [ -n "$PLAN_FILE" ]; then
        if [ ! -f "$PLAN_FILE" ]; then
            log_error "Plan file not found: $PLAN_FILE"
            exit "$EXIT_NOT_FOUND"
        fi
        return
    fi

    local found
    found=$(find . -maxdepth 1 -name 'Implementation_plan-*.md' | sort | head -1)

    if [ -z "$found" ]; then
        log_error "No Implementation_plan-*.md file found in the current directory."
        log_info "Specify the plan file explicitly as one of the arguments."
        exit "$EXIT_NOT_FOUND"
    fi

    PLAN_FILE="$found"
    log_info "Using plan file: $PLAN_FILE"
}

# ============================================================================
# Main
# ============================================================================

main() {
    parse_args "$@"

    [ "$VERBOSE" -eq 1 ] && export ERROR_HANDLING_LOG_LEVEL=0

    resolve_plan_file

    local state="complete"
    [ "$UNCOMPLETE" -eq 1 ] && state="incomplete"

    local failures=0
    for task in "${TASK_NUMBERS[@]}"; do
        set_plan_task_complete "$PLAN_FILE" "$task" "$state" || {
            log_error "Failed to mark task $task as ${state}"
            failures=$((failures + 1))
        }
    done

    # Print a summary of overall plan progress
    local counts completed total
    counts=$(count_plan_tasks "$PLAN_FILE")
    completed="${counts%% *}"
    total="${counts##* }"
    log_info "Progress: $completed/$total tasks complete in $(basename "$PLAN_FILE")"

    [ "$failures" -eq 0 ] || exit "$EXIT_GENERAL_ERROR"
}

main "$@"
