#!/usr/bin/env bash
# markdown-plan-complete-task.sh - Mark a task in an implementation plan as complete or incomplete
# Version: 1.0.0
# Description: Toggles the checkbox state of a single task in a markdown
#              implementation plan generated by Copilot skills such as
#              devenv-create-implementation-plan or devenv-plan-from-spec.
# Requirements: Bash 4.0+, awk, grep, sed

source "$DEVENV_TOOLS/lib/error-handling.bash"
source "$DEVENV_TOOLS/lib/versioning.bash"

enable_strict_mode

readonly SCRIPT_VERSION="1.0.0"
# shellcheck disable=SC2155
readonly SCRIPT_NAME="$(basename "$0")"

script_version "$SCRIPT_NAME" "$SCRIPT_VERSION" "Mark a task in an implementation plan as complete or incomplete"

source "$DEVENV_TOOLS/lib/markdown.bash"

# ============================================================================
# Global Variables
# ============================================================================

PLAN_FILE=""
TASK_NUMBER=""
UNCOMPLETE=0
VERBOSE=0

# ============================================================================
# Usage
# ============================================================================

show_usage() {
    cat << EOF
Usage: $SCRIPT_NAME [OPTIONS] TASK_NUMBER [PLAN_FILE]

Mark a task checkbox in an implementation plan as complete or incomplete.

Tasks are identified by their dotted number, e.g. "2.3" or "1.4.2", as they
appear in plans generated by devenv-create-implementation-plan or
devenv-plan-from-spec.

Arguments:
    TASK_NUMBER     Dotted task number to update (X.Y or X.Y.Z)
    PLAN_FILE       Path to the markdown plan file.
                    Defaults to the first Implementation_plan-*.md file found
                    in the current directory.

Options:
    -h, --help          Show this help message and exit
    -v, --version       Show version information and exit
    -V, --verbose       Enable verbose output
    --uncomplete        Mark the task as incomplete ([ ]) instead of complete ([x])

Examples:
    # Mark task 2.3 complete in the default plan file
    $SCRIPT_NAME 2.3

    # Mark task 1.4.2 complete in a specific plan file
    $SCRIPT_NAME 1.4.2 /path/to/Implementation_plan-001.md

    # Mark task 2.3 as incomplete (undo)
    $SCRIPT_NAME --uncomplete 2.3

Exit Codes:
    0   Success
    1   General error
    2   Invalid arguments
    3   Missing dependencies
    4   Task not found

EOF
    exit 0
}

# ============================================================================
# Argument Parsing
# ============================================================================

parse_args() {
    local positional=()

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -h|--help)
                show_usage
                ;;
            -v|--version)
                exit 0
                ;;
            -V|--verbose)
                VERBOSE=1
                shift
                ;;
            --uncomplete)
                UNCOMPLETE=1
                shift
                ;;
            -*)
                log_error "Unknown option: $1"
                log_info "Run '$SCRIPT_NAME --help' for usage."
                exit "$EXIT_INVALID_ARGUMENT"
                ;;
            *)
                positional+=("$1")
                shift
                ;;
        esac
    done

    if [ "${#positional[@]}" -lt 1 ]; then
        log_error "TASK_NUMBER is required."
        log_info "Run '$SCRIPT_NAME --help' for usage."
        exit "$EXIT_INVALID_ARGUMENT"
    fi

    TASK_NUMBER="${positional[0]}"

    if [ "${#positional[@]}" -ge 2 ]; then
        PLAN_FILE="${positional[1]}"
    fi
}

# ============================================================================
# Helpers
# ============================================================================

# Resolve the plan file: use the explicit argument if given, otherwise find
# the first Implementation_plan-*.md in the current directory.
resolve_plan_file() {
    if [ -n "$PLAN_FILE" ]; then
        if [ ! -f "$PLAN_FILE" ]; then
            log_error "Plan file not found: $PLAN_FILE"
            exit "$EXIT_NOT_FOUND"
        fi
        return
    fi

    local found
    found=$(find . -maxdepth 1 -name 'Implementation_plan-*.md' | sort | head -1)

    if [ -z "$found" ]; then
        log_error "No Implementation_plan-*.md file found in the current directory."
        log_info "Specify the plan file explicitly: $SCRIPT_NAME $TASK_NUMBER <plan-file>"
        exit "$EXIT_NOT_FOUND"
    fi

    PLAN_FILE="$found"
    log_info "Using plan file: $PLAN_FILE"
}

# ============================================================================
# Main
# ============================================================================

main() {
    parse_args "$@"

    [ "$VERBOSE" -eq 1 ] && export ERROR_HANDLING_LOG_LEVEL=0

    resolve_plan_file

    validate_plan_task_number "$TASK_NUMBER" || exit "$EXIT_INVALID_ARGUMENT"

    local state="complete"
    [ "$UNCOMPLETE" -eq 1 ] && state="incomplete"

    set_plan_task_complete "$PLAN_FILE" "$TASK_NUMBER" "$state" || exit "$EXIT_GENERAL_ERROR"

    # Print a summary of overall plan progress
    local counts completed total
    counts=$(count_plan_tasks "$PLAN_FILE")
    completed="${counts%% *}"
    total="${counts##* }"
    log_info "Progress: $completed/$total tasks complete in $(basename "$PLAN_FILE")"
}

main "$@"
