#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEVENV_ROOT="${DEVENV_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
TARGET_USER="${SUDO_USER:-${USER:-vscode}}"

info() { echo "• $*"; }
warn() { echo "WARN: $*" >&2; }

if ! command -v zsh >/dev/null 2>&1; then
  info "Installing zsh..."
  sudo apt-get update -y
  sudo apt-get install -y zsh
else
  info "zsh already installed"
fi

ZSH_PATH="$(command -v zsh)"

if ! grep -Fq "$ZSH_PATH" /etc/shells; then
  info "Registering $ZSH_PATH in /etc/shells"
  echo "$ZSH_PATH" | sudo tee -a /etc/shells >/dev/null
fi

if getent passwd "$TARGET_USER" >/dev/null 2>&1; then
  current_shell="$(getent passwd "$TARGET_USER" | cut -d: -f7)"
  if [[ "$current_shell" != "$ZSH_PATH" ]]; then
    info "Setting default shell for $TARGET_USER to zsh"
    sudo chsh -s "$ZSH_PATH" "$TARGET_USER"
  else
    info "Default shell for $TARGET_USER already set to zsh"
  fi
else
  warn "Could not look up user $TARGET_USER; skipping default shell change"
fi

ZSHRC="$HOME/.zshrc"
ZSHRC_DEVENV="$HOME/.zshrc.devenv"

info "Writing devenv zsh configuration to $ZSHRC_DEVENV"
cat > "$ZSHRC_DEVENV" <<'EOF'
# Auto-generated by devenv install-extras/zsh.sh
# Zsh configuration that reuses the shared ~/.devenvrc and adjusts prompt/completion for zsh

export DEVENV_ROOT="${DEVENV_ROOT:-/workspaces/devenv}"

# Source the shared configuration (shell-agnostic)
if [ -f "$HOME/.devenvrc" ]; then
  source "$HOME/.devenvrc"
fi

# Configure zsh prompt to match devenv bash prompt style
autoload -Uz vcs_info
precmd() { vcs_info }

# Git prompt configuration with dirty indicator
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' unstagedstr ' %F{yellow}✗%f'
zstyle ':vcs_info:*' stagedstr ' %F{yellow}✗%f'
zstyle ':vcs_info:git:*' formats '%F{cyan}(%F{red}%b%f%u%F{cyan})%f '
zstyle ':vcs_info:git:*' actionformats '%F{cyan}(%F{red}%b%f%F{cyan}|%F{yellow}%a%f%u%F{cyan})%f '

# Build prompt components
_devenv_user_prompt() {
  if [ -n "${GH_USER:-}" ]; then
    echo "%F{green}@${GH_USER}%f "
  else
    echo "%F{green}%n%f "
  fi
}

_devenv_path_prompt() {
  local current_path="${PWD}"
  local devenv_root="${DEVENV_ROOT:-}"
  
  if [[ -n "$devenv_root" && "$current_path" == "$devenv_root/repos/"* ]]; then
    echo "%F{blue}...${current_path#$devenv_root/repos}%f"
  else
    echo "%F{blue}%~%f"
  fi
}

# Set the prompt (with command substitution)
setopt prompt_subst
PROMPT='$(_devenv_user_prompt)$(_devenv_path_prompt) ${vcs_info_msg_0_}%# '

# Basic zsh completion
autoload -U +X compinit
compinit -u
EOF

if [ ! -f "$ZSHRC" ]; then
  info "Creating $ZSHRC"
  touch "$ZSHRC"
fi

MARKER="### devenv zsh integration"
if ! grep -Fq "$MARKER" "$ZSHRC"; then
  info "Adding devenv include to $ZSHRC"
  {
    echo "$MARKER"
    echo "source \"$ZSHRC_DEVENV\""
    echo "$MARKER end"
  } >> "$ZSHRC"
else
  info "$ZSHRC already sources devenv config"
fi

info "zsh setup complete. Open a new terminal or run 'exec zsh' to start using it."
