code --install-extension ms-dotnettools.csdevkit
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension rafistatar.addlocalnetreferences
code --install-extension schneiderpat.aspnet-helper
code --install-extension rogalmic.bash-debug
code --install-extension alefragnani.bookmarks
code --install-extension ms-dotnettools.vscode-dotnet-pack
code --install-extension k--kato.docomment
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension matijarmk.dotnet-core-commands
code --install-extension eamodio.gitlens
code --install-extension tintoy.msbuild-project-tools
code --install-extension quicktype.quicktype
code --install-extension christian-kohler.path-intellisense
code --install-extension dinhani.divider
code --install-extension wayou.vscode-todo-highlight
code --install-extension fullstackspider.visual-nuget
code --install-extension ms-mssql.mssql
code --install-extension cweijan.vscode-redis-client
code --install-extension mongodb.mongodb-vscode
code --install-extension EditorConfig.EditorConfig
code --install-extension humao.rest-client
